//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Character
{
	public virtual int strength
	{
		get;
		set;
	}

	public virtual int intelligence
	{
		get;
		set;
	}

	public virtual int dexterity
	{
		get;
		set;
	}

	public virtual int health
	{
		get;
		set;
	}

	public virtual int life
	{
		get;
		set;
	}

	public virtual int action_points
	{
		get;
		set;
	}

	public virtual int armour
	{
		get;
		set;
	}

	public virtual string name
	{
		get;
		set;
	}

	public virtual IEnumerable<Item> Item
	{
		get;
		set;
	}

	public virtual CharacterClass CharacterClass
	{
		get;
		set;
	}

}

