//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

[Serializable]
public class NodeLink
{
	public virtual Challenge Challenge
	{
		get;
		set;
	}

    public StoryNode From { get; set; }
    public StoryNode To { get; set; }

    public NodeLink()
    {
        From = null;
        To = null;
        Challenge = null;
    }

    public NodeLink(StoryNode from, StoryNode to, Challenge challenge)
    {
        From = from;
        To = to;
        Challenge = challenge;
    }
    public NodeLink(StoryNode from, StoryNode to)
    {
        From = from;
        To = to;
    }
}

