//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

[Serializable]
public class StoryNode
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual string story_content
	{
		get;
		set;
	}

    public StoryNode() { }

}

