//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Consumable : Item
{
	public virtual int bonus
	{
		get;
		set;
	}

	public virtual string subject
	{
		get;
		set;
	}

}

