//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Item
{
	public virtual int weight
	{
		get;
		set;
	}

	public virtual string name
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

}

